### ISSUE TITLE
Add filters on term lists.

### ISSUE THREAD

**Issue by johnsmithodom** [hbstack/blog#115]
here is an example, which should make hbstack really stands out. Thank you.
https://gronskiy.com/tags/web/

**Comment by johnsmithodom** [comment]
> > is that a way to select both #Search and #DocSearch tags at the same time, where visitors scan just look at doc with #Search and #DocSearch at the same time.
> 
> That's possible, but it'll just filter the current list's posts, not all the posts, I don't want to load list data in JS way dynamically on a static site. For example, `/series/docs/` list contains 100 posts, the filters of `/series/docs/` will only be applied on those 100 posts, won't affect the paginated lists, e.g. `/series/docs/page/2`, `/series/docs/page/3`. But you're able to change the `paginate` (how many posts per list) to suit your needs, it should be good for any size of sites.
> 
> The filters below is what I can image:
> 
>     * Year
> 
>     * Tags
> 
>     * Authors
> 
>     * Categories
> 
>     * Series
> 
> 
> I'll work on it tonight if the solution is OK.

so just to make sure we are on the same page to improve hbstack (although I just asking feature)

visitors can choose,   any combinations of “
    Year  (2020,2021,2022,2023)
    Tags (linux, window, mac)
    Authors (ceo, cfo)
    Categories (guide, news)
    Series  (s1,s2,s3)
”
like,  so 2020&2021&ceo   where should return all posts of years of 2020 and 2021 where authors is ceo? ( please notice two years are selected in this case of the same columns) , Not fancy UI is needed, just drop down, where visitors check to select tags by each columns ? 
just ex:

2020,2021,2022 are selected return all those post with such those tags.
2020,2021,2022, window, mac and cfo are selected return all those post with such those tags, but with condition of  posts with window, mac and written by cfo.

yes. understand to keep good performance, we may need to avoid JS,  (maybe JS solution the solution,  but not as default; only when users of HBStack want good functions and ok with the performance result since it would be a good balance？）

**Comment by razonyang** [comment]
> 2020&2021&ceo where should return all posts of years of 2020 and 2021 where authors is ceo in all posts?

Hi, thanks for explanation.

The JS is the only way to handle **all** posts, I could create indices for all posts, filter and show the results, but I'm not going to implement this (_filtering **all** posts_) on the _list pages_ for some main reasons:

1. SEO: RAW HTML are always preferred, avoid using JS as possible.
2. Complicated: I don't want to combine both of JS and RAW HTML to render the every list pages and theirs pagination, it makes things worse.
3. Btw, the example sites you mentioned are putting all related posts in the same single pages, and filtering posts *in place*. This approach works fine on a small site, but it may become an issue if there are hundreds or even thousands of posts on a list. It's no difference with the [solution above](https://github.com/hbstack/blog/issues/115#issuecomment-1519325821), you can control how many posts per page, and filter posts in place.

> we can just "build" all possible combinations first.

I think that's impossible to create those combinations pages automatically during the build stage.

It sounds more like a search page request.

**Comment by johnsmithodom** [comment]
> It sounds more like a search page request.

yes, you are right. seem like it as well.  if search can handle it, why can't just tag? where we pre-build the tags for pre-defined result?
"I think that's impossible to create those combinations pages automatically during the build stage.”  （kind of disagree)
 (maybe we need to run a custom script to "build" up all the tags then, run hugo build?

**Comment by razonyang** [comment]
> (maybe we need to run a custom script to "build" up all the tags then, run hugo build?

To be clarified, I think we're talking about the prebuilt pages (pure HTML) for all combinations of taxonomies. e.g. `/tags/tag1-tag2`, `/tags/tag-2-tag-3` and so on, if so, just image that, how many combinations pages on a regular site with 100 tags (probably `100! - 100` pages). Other than that, I haven't combined it with the categories, the authors and the years.

That's why I said that's impossible, and the JS is the only way to do that.

**Comment by johnsmithodom** [comment]
yes. was thinking per-build though pages， but not really doing the math at the same time.  


> That's why I said that's impossible, and the JS is the only way to do that.

so you decided to build a module within the HBStack for this feature  with JS? 

Really like HBStack where it provides "whole" package as a solution,  where using one framework can build multiple different purpose sites.

**Comment by razonyang** [comment]
> so you decided to build a module within the HBStack for this feature with JS?

Still considering on it, let me summary it up.

You want to filter the **all** posts in the list pages **in current page** (not opening a new page to search), which have to render and paginate **in both HTML and JS ways**, it looks like that include a search page into the list page which I don't like to do, since it complicates the page, for example, we have to hide the original rendered content (posts list and pagination navigation) when performing a search, and re-render the results and create a new pagination navigation according to the results in JS.

We could open a new page to process the filters, **but this feature overlaps with the search module**, it makes more sense to add taxonomies filter on the search modal.

![image](https://user-images.githubusercontent.com/17720932/233961758-10970347-579d-4d9b-904f-4103fb7a9a33.png)

**Comment by johnsmithodom** [comment]
yes,  you are right,  wonder how we can handle the case where 2021 and 2022 are selected.  (assuming we add   taxonomies filter on the search modal.) since we can only choose one from one column, like below Language （or we can choose all from the column) 
![image](https://user-images.githubusercontent.com/120798996/234064344-0eeb7c0d-2a9f-4d10-a9f0-0df03c69a1b4.png)

Honestly, since  hbstack framework is build with modules, it would make more sense to have a modules for filtering whether with CSS and HTML or JS.  
Maybe we could have a filter search page ?  like a search page for complicated filtering. 

Thank you for keeping the discussion open and sharing the reasons with it.

**Comment by razonyang** [comment]
> wonder how we can handle the case where 2021 and 2022 are selected. (assuming we add taxonomies filter on the search modal.) since we can only choose one from one column, like below Language （or we can choose all from the column)

The select input (dropdown) can have multiple options, e.g. select 2023 and 2022 at the same time.

Planed, but not high priority, probably a search page.

**Comment by johnsmithodom** [comment]
Thank you for accepting this feature, which makes hbstack really stand out comparing to other open source out them with the rest of package from hbstack, can't wait this feature. Thank you again.

**Comment by razonyang** [comment]
Those features were introduced in the search module `v0.3.1`, I don't want to repeat the dynamic thing in list page, hope this suit your needs.

![image](https://github.com/hbstack/blog/assets/17720932/1a38ea63-ece9-430b-9539-dce049cfd07d)
