### ISSUE TITLE
after following the installation guide,  please help.  guide from https://hbstack.dev/en/docs/getting-started/installation/

### ISSUE THREAD

**Issue by johnsmithodom** [hbstack/blog#119]
Start Hugo Server[§](https://hbstack.dev/en/docs/getting-started/installation/#start-hugo-server)
Preview in Development Mode
npm run dev

> dev
> hugo server --gc --disableFastRender --enableGitInfo -D

Error: unsupported redirect to value "/404.html" in server config; currently this must be either a remote destination or a local folder, e.g. "/blog/" or "/blog/index.html"

env.  information.
ubunmac@ubunmac-MacBookPro:~/dev/blog$ go version
go version go1.18.1 linux/amd64
ubunmac@ubunmac-MacBookPro:~/dev/blog$ hugo version
hugo v0.92.2+extended linux/amd64 BuildDate=2023-01-31T11:11:57Z VendorInfo=ubuntu:0.92.2-1ubuntu0.1
ubunmac@ubunmac-MacBookPro:~/dev/blog$ node
Welcome to Node.js v12.22.9.

**Comment by razonyang** [comment]
Hi @johnsmithodom, this theme and its modules require Hugo (extended) `v0.111.3`, should be fixed after upgrading Hugo.
