### ISSUE TITLE
Summaries truncated indicator (dots) seems not work well with `<!--more-->`.

### ISSUE THREAD

**Issue by razonyang** [hbstack/blog#387]
i.e.

```markdown
This module ships with an universal pagination template, which allows configuring by parameters, such as alignment, size and the number of siblings.

<!--more-->
```

![image](https://github.com/hbstack/blog/assets/17720932/7e645843-7981-4876-a42d-950c8240a94f)

I'd like to revert the #374 change, @TetraTheta what do you think?

**Comment by razonyang** [comment]
I replaced it with a read more button, it should be better to clients to continue reading and get better experience (no need to find and click the title).

Could you do me a favor for translating the item read_more in Korean?

**Comment by TetraTheta** [comment]
> Could you do me a favor for translating the item read_more in Korean?

Done in #389
