### ISSUE TITLE
Setting "defaultContentLanguageInSubdir" to "false" breaks archives for default language

### ISSUE THREAD

**Issue by whiztech** [hbstack/blog#427]
Tested with HB Theme Template using default configurations except setting `defaultContentLanguageInSubdir` to `false`.

Archives under different language in language subdir (zh-hans) works fine. Archives for the default language not in language subdir is broken. Year and month section is showing all archives instead of yearly and monthly posts.

**Comment by razonyang** [comment]
Thanks for the feedback, fixed since `v0.19.1`, please upgrade via `hugo mod get -u github.com/hbstack/blog@v0.19.1`.
