### ISSUE TITLE
Categories, Series, Tags doesn't respect params.hb.blog.paginate value

### ISSUE THREAD

**Issue by TetraTheta** [hbstack/blog#440]
By default, `params.hb.blog.paginate` value is `9`. I've changed it to `12` so that it can be displayed nicely with 2, 3, 4 columns.

That value is respected in 'default view' which displays 'posts'. But it is ignored in Categories, Series, Tags view and they always paginates 9 posts in a page.

I couldn't find any documentation about setting their `paginate` value, so I presume this is a unintended bug.

---

You can inspect [my blog](https://tetralog.haipa.xyz/) for example. It displays 12 posts in 'page view', but in [category view](https://tetralog.haipa.xyz/categories/%EC%9B%90%EC%8B%A0/), [series view](https://tetralog.haipa.xyz/series/%EC%84%A0%EC%9C%A8%EC%9D%B4-%ED%9D%90%EB%A5%B4%EB%8A%94-%EB%B0%A4/), [tag view](https://tetralog.haipa.xyz/tags/%EC%B6%95%EC%9B%94%EC%A0%88/)(Sorry, this tag doesn't have enough posts about it), they don't align with 'page view'.

In page view, posts are displayed with 3x4. In other view, posts are displayed with 2x5.

**Comment by razonyang** [comment]
If I remmember correctly, the paginate parameter is `hb.terms.paginate` for term list pages, probably undocumented, please try again, will fixes the docs later, PR are also welcome.

**Comment by TetraTheta** [comment]
Setting `params.hb.terms.pagiate` puts 12 posts in a page, but it still doesn't respect 3x4 layout. Instead, I get 2x6 layout.

Is this intended behavior? Because, I want them to be 3x4 layout so that it matches layout to 'page view'. 2x6 is too wasteful in wide screen.

**Comment by razonyang** [comment]
Done, upgrade to the latest blog module should work.

**Comment by TetraTheta** [comment]
Thank you for fast work!
