### ISSUE TITLE
Decap CMS preview template replace the placeholder `data widgets` with empty string

### ISSUE THREAD

**Issue by pleasantone** [hbstack/blog#627]
https://github.com/hbstack/blog/blob/6da72fb05a02e2fd051b166e1a7822e32aca3568/modules/decap-cms/assets/decap-cms/preview-templates/hb/blog-post.ts#L66

<img width="735" alt="Screenshot 2024-02-01 at 5 07 55 PM" src="https://github.com/hbstack/blog/assets/5339793/371748ea-65d4-4505-8b38-d1e280c36ae5">

**Comment by razonyang** [comment]
I've asked this on Discord channel https://discord.com/channels/1078661770119487600/1078661770119487603/1200636212826886165.

PR arewelcome if you have a solution.

**Comment by pleasantone** [comment]
I'm sorry, I don't see the discord server documented... do I need an invite to join?

**Comment by razonyang** [comment]
No problem. Here you go https://decapcms.org/community/.
