### ISSUE TITLE
Allow changing post card-Image aspect ratio

### ISSUE THREAD

**Issue by m29h** [hbstack/blog#802]
Currently post/card-img aspect ratio seems to be determined by fixed height of 160pixels and variable width 100%

Practically this gives an aspect ratio that is quite wide. I would prefer being able to adjust this aspect ratio by increasing image height. Can the height be put into user configurable parameter maybe? Also the resizing height of thumbnail image (currently hardwired to 360px should change accordingly)
Thank you

**Comment by razonyang** [comment]
It's good to have, may happen in this week.

**Comment by razonyang** [comment]
Available since [github.com/hbstack/blog@v0.31.0](https://github.com/hbstack/blog/releases/tag/v0.31.0), see #809 to detailed usage.

**Comment by razonyang** [comment]
Please keep in mind that, for the sake of alignment and responsiveness, most of the time, the display image is incomplete.

https://github.com/hbstack/blog/assets/17720932/bcd8a480-b3e7-4492-bd99-aba5bdf04cf7

But you can add custom style to show full image all the time, but it may not look good.

```
.hb-blog-post-card-img {
  height: 100%;
  // or replace with the follows.
  object-fit: contain;
}
```
