### ISSUE TITLE
Sidebar posts module and related posts module are broken when `post_thumbnail` is `false`

### ISSUE THREAD

**Issue by razonyang** [hbstack/blog#813]
![image](https://github.com/hbstack/blog/assets/17720932/484c815f-e438-4089-b7e8-59bac9480367)

**Comment by razonyang** [comment]
## Solution 3

Add `vertical` style for those two modules that look nice without thumbnails, for example.

![image](https://github.com/hbstack/blog/assets/17720932/bc28e942-432b-4fce-8602-ef0c4854aab6)

**Comment by FuadEfendi** [comment]
@razonyang thank you for quick response!

I also tried this, `post_thumbnail_resize_height: 14` - but I don't see any difference. 

Maybe putting arrows below title?

**Comment by FuadEfendi** [comment]
yes, Solution 3 looks nice
