### ISSUE TITLE
Bug/Typo in layouts/partials/hb/modules/blog/posts.html

### ISSUE THREAD

**Issue by Gordolin** [hbstack/blog#945]
There is a missing right angle bracket in line 8 of layouts/partials/hb/modules/blog/posts.html.

Also there is a bug in the code, so it is not simple fix the typo.

**Comment by razonyang** [comment]
Hi, the closing bracket does present, is the HTML output incorrect?
https://github.com/hbstack/blog/blob/main/layouts%2Fpartials%2Fhb%2Fmodules%2Fblog%2Fposts.html#L12-L12

**Comment by Gordolin** [comment]
Hi, im sorry. I haven't seen the closing angle bracket in line 12.

I tried somthing with the code, i thougt there is a missing angle bracket an tried to fix it, which throws at least errors (of course). That was my mistake.

**Comment by razonyang** [comment]
No problem.
